import { Inter } from 'next/font/google';
import Head from 'next/head';
import type { ReactElement } from 'react';

import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

const Home = (): ReactElement => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={`${styles.main} ${inter.className}`}>
      <div className={styles.description}>
        <p>
          Get started by editing&nbsp;
          <code className={styles.code}>src/pages/index.tsx</code>
        </p>
      </div>
    </main>
  </>
);

export default Home;
